steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/kairei-http
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/kairei-http
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - kairei-http
      - "--image"
      - gcr.io/$PROJECT_ID/kairei-http
      - "--region"
      - $_REGION
      - "--set-secrets=/etc/secrets/http/kairei-http-secret.json=KAIREI_HTTP_DEV:latest"
      - "--set-secrets=/etc/secrets/system/kairei-system-secret.json=KAIREI_HTTP_SYSTEM_DEV:latest"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: asia-northeast1
